const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..', '..')
const workflow = fs.readFileSync(path.join(root, '.github/workflows/deploy-preview.yml'), 'utf8')
const packageJson = require(path.join(root, 'package.json'))

test('deploys changed cloud functions with miniprogram-ci and the WeChat upload key', () => {
  expect(packageJson.scripts['ci:deploy-functions']).toBeUndefined()
  expect(packageJson.devDependencies['@cloudbase/cli']).toBeUndefined()
  expect(workflow).toContain('npm install --no-save miniprogram-ci@2.1.31')
  expect(workflow).not.toContain('@cloudbase/cli')
  expect(workflow).not.toContain('TENCENT_SECRET_ID')
  expect(workflow).not.toContain('TENCENT_SECRET_KEY')
  expect(workflow).toContain('name: Patch miniprogram-ci function creation')
  expect(workflow).toContain('ResourceNotFound.Function')
  expect(workflow).toContain('miniprogram-ci uploadFunction patch target not found')
  expect(workflow).toContain('npx miniprogram-ci cloud functions upload')
  expect(workflow).toContain('--appid wxcabf6afa48b9277d')
  expect(workflow).toContain('--pkp "$WECHAT_PRIVATE_KEY_PATH"')
  expect(workflow).toContain('--env cloudbase-d7gx0ikiwa58549a4')
  expect(workflow).toContain('--name "$function_name"')
  expect(workflow).toContain('--path "./cloudfunctions/$function_name"')
  expect(workflow).toContain('--remote-npm-install true')
})

test('prepares the WeChat key before deploying functions, uploading preview, and generating QR', () => {
  const prepareIndex = workflow.indexOf('name: Prepare WeChat upload')
  const deployIndex = workflow.indexOf('name: Deploy changed cloud functions')
  const uploadIndex = workflow.indexOf('name: Upload WeChat preview')
  const generateQrIndex = workflow.indexOf('name: Generate WeChat preview QR')
  const uploadArtifactIndex = workflow.indexOf('name: Upload WeChat preview QR artifact')
  const cleanupIndex = workflow.indexOf('name: Clean up WeChat upload key')

  expect(prepareIndex).toBeGreaterThan(-1)
  expect(deployIndex).toBeGreaterThan(prepareIndex)
  expect(uploadIndex).toBeGreaterThan(deployIndex)
  expect(generateQrIndex).toBeGreaterThan(uploadIndex)
  expect(uploadArtifactIndex).toBeGreaterThan(generateQrIndex)
  expect(cleanupIndex).toBeGreaterThan(uploadArtifactIndex)
  expect(workflow).toContain('name: wechat-preview-qrcode')
  expect(workflow).toContain('path: ${{ runner.temp }}/wechat-preview-qrcode.png')
})
